version: "25.0.3"
services:

  job_api:
    container_name: job_api
    build:
      context: .
    env_file:
      - .env
    networks:
      - my_network
    ports:
      - 5002:5002
    depends_on:
      - boardjob_db
      - job_ebs
      
  boardjob_db:
    container_name: BoardJobDatabase
    image: microsoft/mssql-server-linux
    networks:
      - my_network
    env_file:
      - containers/db/db.env
  
  job_esb:
    container_name: project_esb
    image: rabbitmq:6-project
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge